title:            Andreanisme Net
description:      unless otherwise noted
logo:             logo.png
disqus_shortname: andreanismesnote
# Assign a default image for your site's header and footer
default_bg:       hero.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true

# Turn on or off the fin animations in the header and footer
triangleheader:   true
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"

url:              "http://andreanisme.net/"


# Owner/author information
owner:
  name:           Andrean Saputro
  avatar:         logo.png
  email:          andreanisme@gmail
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    My name is Andrean Saputro
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:		  "andreanisme"
  facebook:		  "andrean"
  github:	      "andreanisme"
  linkedin:       "http://www.linkedin.com/in/andreanisme"
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "https://plus.google.com/u/1/+AndreanSaputro"

# Analytics and webmaster tools stuff goes here
google_analytics: UA-43055503-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: About
    url: /about
  - title: Categories
    url: /categories

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Jakarta
future:      true
markdown:    kramdown
paginate:    6
pygments:    true
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
